### ISSUE TITLE
header index 

### ISSUE THREAD

**Issue by sarahsweet** [lukaswenzl/astrometry#5]
Running on HST or HSC images fails, perhaps because the header in those files is stored with the science extension [1] instead of the primary extension [0]. 

```
$ pwd
/Users/ssweet/astrometry
$ python astrometry.py hst/ienh34010_drz_f140w.fits
> Astrometry for hst/ienh34010_drz_f140w.fits 
Traceback (most recent call last):
  File "astrometry.py", line 1001, in <module>
    main()
  File "astrometry.py", line 474, in main
    images=images, vignette=args.vignette,vignette_rectangular=args.vignette_rectangular, cutouts=args.cutout, ra=args.ra, dec=args.dec, projection_ra=args.projection_ra, projection_dec=args.projection_dec, verbose=verbose, save_images=args.save_images, ignore_header_rot=args.ignore_header_rot, radius = args.radius, save_bad_result=args.save_bad_result, silent =args.silent, sigma_threshold_for_source_detection= args.sigma_threshold_for_source_detection, high_res=args.high_resolution, hdul_idx=args.hdul_idx, filename_for_sources=args.filename_for_sources, FWHM=args.seeing)
  File "astrometry.py", line 765, in astrometry_script
    image_or = hdul[hdul_idx].data.astype(float)
AttributeError: 'NoneType' object has no attribute 'astype'
```

**Comment by lukaswenzl** [comment]
When you run the code you can specify what index in the fits file your images are at with the following flag: " --hdul_idx 1"
Hope that resolves the issue

**Comment by sarahsweet** [comment]
Thanks, that works!
